#! python3
# takes image from the first page, downloads it and opens in tab

import requests
from bs4 import BeautifulSoup
import webbrowser
import os
browser_path = r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
webbrowser.register('mozzila', None, webbrowser.BackgroundBrowser(browser_path))

url = 'http://xkcd.com/1/'
url_get = requests.get(url)
soup = BeautifulSoup(url_get.content, 'lxml')
text = soup.select_one('#ctitle').text
link = soup.find('div', id='comic').find('img').get('src')
link = link.replace('//', 'http://')

# Image title and link
print(f'{text}\n{link}')

# Download image
img_name = os.path.basename(link)     
img = requests.get(link)              
with open(img_name, 'wb') as f_out:   
	f_out.write(img.content)          

# Open image in browser or default image viewer
webbrowser.get('mozzila').open_new_tab(link)
